sudo: required
services:
    - docker

before_install:
    - docker build -t dmuziga/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dmuziga/docker-react npm run test

deploy:
	provider: elasticbeanstalk
	access_key_id: $AWS_ACCESS_KEY
	secret_access_key: $AWS_SECRET_KEY
	region: ¨us-east-2¨
	app: "docker-react"
	env: "docker-react-env"
    bucket_name: ¨elasticbeanstalk-us-east-2-775491092246
    on:
        branch: master