language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dmuziga/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dmuziga/docker-react npm run test

