sudo: required
services:
    - docker

before_install:
    - docker build -t dmuziga/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dmuziga/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ¨us-west-2¨
    app: ¨frontend¨
    env: ¨Frontend-env¨
    bucket_name: ¨elasticbeanstalk-us-west-2-775491092246¨
    bucket_path: ¨frontend¨
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        